services:
    app.repository.movie:
        class: AppBundle\Repository\MovieRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: ['AppBundle\Entity\Movie']
        public: true
